name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses:  ./.github/actions/node-install
      
      # - name: Run knip (unused files/deps check)
      #   run: pnpm run knip

      - name: Run Tests 
        run: pnpm test

      - name: Build
        run: pnpm build
