name: 'PR Review Reminder'

on:
  pull_request:
    types: ['opened', 'ready_for_review']

permissions:
  pull-requests: write

jobs:
  checkPRs:
    if: ${{ github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action ==  'ready_for_review') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses:  actions/setup-node@v4
        with:
          version: 'latest'
          cache: pnpm
      
      - name: Check user's PRs awaiting review
        id: parse-prs
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const username = context.payload.pull_request.user.login;
            core.info(`username: ${username}`)

            const  pullRequests  = await github.paginate( github.rest.pulls.list, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              sort: 'created',
              direction: 'asc',
              per_page: 100,
            });

            const userPullRequests = pullRequests.filter(pr => pr.user?.login === username && pr.state === 'open' && pr.draft === false);
            const prCount = userPullRequests.length;
            core.info(`PR Count for ${username}: ${prCount}`);

            if (prCount > 3) {
              const body = `🚨 @${username} has ${prCount} pull requests awaiting review. Please consider reviewing them when possible. 🚨`;
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.pull_request.number,
                body,
              });
            }
